local_costmap:
   global_frame: odom
   #global_frame: /odom_combined
   robot_base_frame: base_footprint
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05
   transform_tolerance: 2.0
   map_type: costmap

   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: pointcloud_layer, type: "costmap_2d::VoxelLayer"} #Laser sensors
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
#  - {name: range_sensor_layer,   type: "range_sensor_layer::RangeSensorLayer"}
